//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zags.OrganizationService.AcceptanceTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatasetsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatasetsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zags.OrganizationService.AcceptanceTests.Properties.DatasetsResource", typeof(DatasetsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Organization]  ([RaisonSociale],[Reference],[Effectif],[FormeJuridique],[CodeNAF],[IdentifiantConventionCollective],[SIRET],[AggregateId], [Version])
        ///     VALUES         (&apos;The First Test Company&apos;, &apos;C37805E9-6D6B-49BF-B667-B74ABBC34D13&apos; , 50, &apos;SARL&apos;, &apos;30483304804522&apos;, &apos;0044&apos;, &apos;732829320&apos;, &apos;173F41CF-C7D0-4829-9834-F05DAC7C9F07&apos;, 1)
        ///	 GO
        ///INSERT INTO [Organization]  ([RaisonSociale],[Reference],[Effectif],[FormeJuridique],[CodeNAF],[IdentifiantConventionCollective],[SIRET],[AggregateId], [Versio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrganizationDataset {
            get {
                return ResourceManager.GetString("OrganizationDataset", resourceCulture);
            }
        }
    }
}
